config/routes.rb
Rails.application.routes.draw do
  get 'items/dummy'
  resources :items, only: [:new, :create, :index, :show, :destroy]
  devise_for :users
  root to: 'pages#landing'

  resources 'trades', only: [:new, :create, :index, :show] do
   resources :messages, only: :create
  end

  get '/items' => "items#index", :as => :user_root



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  has_many :trades
  has_many_attached :photos
  before_save :image_count
  validates :photos, presence: true
  validates :name, presence: true
  validates :size, presence: true
  # validates :size, presence: true (once the sizing gets done then the turn on the validation)

private
  def image_count
    errors[:base] << "you must upload an image" if self.photos.empty?
    errors[:base] << "you can only upload 3 images" if self.photos.length > 3
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :trade
  scope :unread, ->(){where(read: false)}
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :item_1, class_name: 'Item', foreign_key: 'item_1_id'
  belongs_to :item_2, class_name: 'Item', foreign_key: 'item_2_id'
  has_many :messages


  def random
    all.shuffle.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :messages
  has_many :items, foreign_key: 'owner_id'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def trades
    item_ids = items.pluck(:id)
    Trade.where(item_1_id:item_ids).or(Trade.where(item_2_id:item_ids))
  end

  def unread_messages
    Message.unread.where(trade_id: trades.pluck(:id)).where.not(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :photo])

    # # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def show_navbar
    @show_navbar = true
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :show_navbar, only: [:new, :show, :index]

  def new
    @new_item = Item.new
  end

  def create
    @new_item = Item.new(strong_params)
    @new_item.owner = current_user
    @new_item.save
    if @new_item.save
      redirect_to new_trade_path(item_id: @new_item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.owner_id)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy!
    redirect_to '/items', :notice => "Your item has been deleted"
  end

  def dummy
    # this one's just for making the card
    # component dummy site function
  end

  private

  def strong_params
    params.require(:item).permit(:name, :description, :size, photos: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :show_navbar, only: [:new, :show, ]
  def create
    @trade = Trade.find(params[:trade_id])
    @message = Message.new(message_params)
    @message.trade = @trade
    @message.user = current_user

    if @message.save!
      redirect_to trade_path(@trade, anchor: "message-#{@message.id}")
    else
      render 'trades/show'
    end
  end

  def message_params
    params.require(:message).permit(:message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:landing]

  def landing
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :show_navbar, only: [:index, :show]

  def new
    return redirect_to items_path if current_user.items.empty?
    @all_items = current_user.items
    @user_item = @all_items.shuffle.first unless params[:item_id]
    @user_item ||= @all_items.find(params[:item_id])
    @bigger_item = Item.where("size >= ?",@user_item.size).where.not(owner_id: current_user.id).shuffle.first
    @better_item = Item.where("size <= ?",@user_item.size).where.not(owner_id: current_user.id).shuffle.first
    @bigger_trade = Trade.new(item_1: @user_item, item_2: @bigger_item)
    @better_trade = Trade.new(item_1: @user_item, item_2: @better_item)
  end

  def create
    if exists = Trade.find_by(trade_params_reversed)
      exists.update(matched: true)
      redirect_to trades_path
      return #nil
    end
    unless Trade.find_by(trade_params) #find_or_create_by!
      Trade.create!(trade_params)
    end
    redirect_to new_trade_path
  end

  
  def show
    @trade = Trade.find(params[:id])
    @message = Message.new
  end
  
  def index
    @trades = current_user.trades
  end
  
  private

  def trade_params
    params.require(:trade).permit(:item_1_id, :item_2_id)
  end

  def trade_params_reversed
    {item_1_id: trade_params[:item_2_id], item_2_id: trade_params[:item_1_id]}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/dummy.html.erb
<div class="container">
  <br>
  <h2 class="text-center">Container</h2>
  <%= link_to "Back to landing page", root_path %>
  <p>This is the first container. </p>
  <div>
    <h2> Avatars</h2>
    <%=image_tag("jazz.jpg", :class => "avatar-35")%>
    <%=image_tag("jazz.jpg", :class => "avatar-55")%>
    <%=image_tag("jazz.jpg", :class => "avatar-100")%>
    <%=image_tag("jazz.jpg", :class => "avatar-120")%>
    <h2> Circle Images</h2>
    <%=image_tag("Chair1.jpg", :class => "avatar-65-image")%>
    <%=image_tag("fork.jpg", :class => "avatar-100-image")%>
    <%=image_tag("add_photo.jpg", :class => "avatar-120-image")%>
    <%=image_tag("Chair1.jpg", :class => "avatar-150-image")%>
    <h2>Buttons</h2>
    <a href="#" class="button sm-btn">Small Button</a>
    <a href="#" class="button lg-btn">Large Button</a>
    <a href="#" class="outline-btn">Add Photos</a>
    <a href="#" class="game-btn">SKIP</a>
    <h2>Game Cards</h2>
    <div class="game-card">
      <%=image_tag("Chair1.jpg")  %>
    </div>
    <br>
    <br>
  </div>
</div>

app/views/items/index.html.erb
<div class='row justify-content-center d-flex'>
</div>
</div>
<div class='index-container'>
  <div class='row justify-content-center d-flex'>
    <div class='col-10' align='center'>
      <%=image_tag(current_user.photo, :class => "avatar-120") if current_user.photo.attached? %>
      <h5><b>Hello <%=current_user.name%>!</b></h5>
      <!-- <div class="button sm-btn">
        <%#= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "logout-btn btn button sm-btn" %>
      </div> -->
      <p><%=current_user.address%></p>
      <% if current_user.items.length >= 10 %>
        <p class="size-18"><strong>You have reached the maximum number of items. <br>
            Delete an item to upload a different item.</strong></p>
      <% elsif current_user.items.empty? %>
        <p class="size-18">Add your first item</p>
      <% end %>
      <% current_user.items.each do |item| %>
        <%= link_to item_path(item.id) do %>
          <%=cl_image_tag item.photos.last.key, class:"dashboard-item" if item.photos.attached?%>
        <% end %>
      <% end %>
      <%= link_to new_item_path, data: {turbolinks:false} do %>
        <% unless current_user.items.length >= 10%>
          <%=image_tag("add_photo.jpg", :class => "avatar-120-add-item") %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<%# Om jeg legge til en HTML-klasse: %>
<%# , wrapper_html: { class: 'class_name' } %>
<div class="new-item-container">
  <div>
    <div class='arrow '>
        <div class="title-white ">
          <a class="material-icons arrow" href="javascript:history.back()">keyboard_backspace</a>
          <h1>Add item</h1>
        </div >
    </div>

  </div>
    <div class="white-wrapper">
      <%= simple_form_for @new_item do |f| %>
      <div id="preview"></div>
         <div class= "btn-wrapper upload-btn-wrapper">
          <label class="file required btn-upload" for="item_photos"><span class="material-icons icon-space">perm_media</span>Upload images <abbr title="required">*</abbr></label></div>
            <%= f.input :photos, as: :file, input_html: { multiple: true }, wrapper_html: { class: "img-upload-btn" }, id: "browse" %>
        <!-- <span class="material-icons outline-btn ">perm_media</span> -->
        </div>
          <div class="text-container">
            <%= f.input :name, label: 'Item name' %>
            <%= f.input :description, as: :text, label: 'Description (optional)' %>
          </div>
        <%#= f.input :size, collection: 1..6, as: :select, label: 'Your items size is equal to or larger than a ...' %>
        <div>
          <div class='container-show-text'>
            <h2 class='text-center' id='body-font'> Would you say your item is equal to or smaller than:</h2>
          </div>
         <!--  <div class='container-show-text-b'>
            <p>Clicking on one of the following icons will save your item into a size category and launch you into trade!</p>
          </div> -->
        </div>

        <div class=wrapper>
          <div class='container-sizechart'>
            <div>
              <button name="item[size]" value="1">
                <%=image_tag("fork.jpg", :class => "avatar-120")%>
              </button>
              <p>fork</p>
            </div>
          <div>
            <button name="item[size]" value="2">
              <%=image_tag("book.jpg", :class => "avatar-120")%>
            </button>
            <p>book</p>
           </div>
        </div>

        <div class='container-sizechart'>
          <div>
            <button name="item[size]" value="3">
              <%=image_tag("Coffee Table.jpg", :class => "avatar-120")%>
            </button>
            <p>coffee table</p>
          </div>
            <div>
              <button name="item[size]" value="4">
                <%=image_tag("Office_Chair.jpg", :class => "avatar-120")%>
              </button>
              <p>office chair</p>
            </div>
        </div>

        <div class='container-sizechart'>
          <div>
            <button name="item[size]" value="5">
              <%=image_tag("fridge.jpg", :class => "avatar-120")%>
            </button>
            <p>refrigerator</p>
          </div>
            <div>
              <button name="item[size]" value="6">
                <%=image_tag("Car.jpg", :class => "avatar-120")%>
              </button>
              <p>car</p>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
  <div>
    <div class="show-item" align="center">
      <%= render "shared/carousel" %>
    </div>
    <div class="show-text-con">
      <a class="material-icons arrow" href="javascript:history.back()">keyboard_backspace</a>
        <div>
          <h1> <%= @item.name %></h1>
          <p> Description: <%= @item.description %> </p>
        <!-- <p> Owned by:  <strong> <%#= @user.name %> </strong> </p> -->
          <p> Item added: <%= @item.created_at %></p>
        </div>

        <div class="white-btn">
          <%= link_to "Delete", @item, :confirm => "Are you sure?", :method => :delete%>
        </div>
      </div>
    </div>

    <div class='new-item-container'>
      <div class="d-flex align-items-center">
        <div class="flexbox">
            <%=image_tag(current_user.photo, :class => "avatar-120") if current_user.photo.attached? %>
            <div class="flex-margin">
              <h5><b><%=current_user.name%>!</b></h5>
              <p> Item location:  <strong> <%= @user.address %> </strong> </p>
            </div>
        </div>
      </div>
  </div>


<%# User avatars don't exist yet %>
<%# @user.photo.attached? %>
<%#= raise %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bigger Or Better - Trade your stuff!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Don't throw out your stuff! Trade it for something bigger or better.">
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <%=favicon_link_tag%>
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <% if @show_navbar %>
      <footer>
        <nav class="nav">
          <%= link_to trades_path, class: "nav__link" do %>
            <div class="chat-wrapper">
              <div class="unread"><%= current_user.unread_messages.count %></div>
              <i class="material-icons nav__icon">chat_bubble_outline</i>
            </div>
            <span class="nav__text">Chat</span>
          <% end %>
          <%= link_to new_trade_path, class: "nav__link" do %>
            <i class="material-icons nav__icon" >attach_file</i>
            <span class="nav__text">Play</span>
          <% end %>
          <%= link_to items_path, class: "nav__link" do %>
            <i class="material-icons nav__icon">home</i>
            <span class="nav__text">Home</span>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: "nav__link" do %>
            <i class="material-icons nav__icon">close</i>
            <span class="nav__text">Sign out</span>
          <% end %>
        </nav>
      </footer>
    <% end %>
  </body>
</html>

app/views/pages/landing.html.erb
<div class='land-pad'>
  <div class='row justify-content-center d-flex'>
    <div class='col-10' align='center'>
      <%= image_tag("logo_copy.png", class:'land-logo') %>
      <h5 class='land-tag-line'>Dont throw it out, trade it for something bigger or better.</h5>
    </div>
  </div>
</div>
<br>
<div>
      <div class="get-started mx-auto d-block">
        <%= link_to items_path do %>
          GET STARTED
        <% end %>
      </div>
  <div class='row justify-content-center d-flex'>
    <div class='index-container'>
<div class='container'>
  <div class='row justify-content-center d-flex'>
    <div class='col-10' align='center'>
      <p class='land-text'>
        Do you have something that you don't want anymore? Don't throw it out! Instead, trade it for something else with a neighbor or with someone across town. A game that started door to door with a paper clip and ended with a global fascination is now available in the palm of your hand. Simply take a photo of your item and you're ready to start swiping and tapping and easily trade your unwanted item for something Bigger or Better! </p>
      <div class='container-sizechart'>
        <div class='land-card'><%= image_tag("l1.png", class:'land-imgs') %></div>
        <div class='land-card'><%= image_tag("l4.png", class:'land-imgs') %></div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @item.photos.each do |photo| %>
      <% if @item.photos.index(photo) == 0 %>
        <li data-target="#carouselExampleIndicators" data-slide-to=<%= @item.photos.index(photo).to_s %> class="active"></li>
      <% else %>
        <li data-target="#carouselExampleIndicators" data-slide-to=<%= @item.photos.index(photo).to_s %>></li>
      <% end %>
    <% end %>
  </ol>
  <div class="carousel-inner">
    <% @item.photos.each do |photo| %>
      <% if @item.photos.index(photo) == 0 %>
        <div class="carousel-item active" >
        <% else %>
          <div class="carousel-item" >
          <% end %>
          <%=cl_image_tag photo.key, class:'card-img' %>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert devise-alert-color alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="devise-alert-color alert alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trades/_trade_list_item.html.erb
 <div class="d-flex message-preview">
     <% if message.present? %>

      <%=image_tag(current_user.photo, :class => "avatar-55")%>
     <div class="flex-column">
      <div class="user-name">
        <%= message.user.name %>
      </div>
      <div class="user-message">
        <%= message.message %>
      </div>
      </div>
      <% else %>
    You have a new trade request! Click here to find out who it is from.
    <% end %>
</div>

app/views/trades/index.html.erb
  <div class="container">
  <div class="title-white">
      <a class="material-icons arrow" href="javascript:history.back()">keyboard_backspace</a>
      <h1> Chats </h1>
  </div>
  <div class="all-chats-container">
  <% @trades.each do |trade| %>
    <%= link_to trade_path(trade), class: "user-name" do %>
      <%=render "trade_list_item",message:trade.messages.last %>
    <% end %>
  <% end %>
</div>
</div>

app/views/trades/new.html.erb
<div class="trade-container-top">
  <%# This is the white background at the top %>
</div>
<div class="trade-container-bottom">
  <%# this is the white background at the bottom %>
</div>
<div id="trade-page-body" class='row justify-content-center d-flex inobounce-enable'>
  <div class='col-10' align='center'>
    <% if @bigger_item.nil? %>
     <div class="game-card">
         no item avaialable
        </div>
    <% else %>
      <%= link_to item_path(@bigger_item.id) do %>
        <div id="drag-bigger" class="game-card">
          <% @item = @bigger_item %>
          <%= render "shared/carousel" %>
        </div>
      <% end %>
      <%= form_with(model: @bigger_trade, id: "formBigger") do |f| %>
        <%= f.hidden_field :item_1_id %>
        <%= f.hidden_field :item_2_id %>
      <% end %>
    <% end %>

    <div>
      <div class="hidden-form">
        <%= form_with(url: new_trade_path, method: "get", id: "selectForm", local: true) do |f| %>
          <input type="hidden" name="item_id">
          <%#= hidden_field(:item_id, :id) %>
          <%#= select_tag(:item_id, options_for_select(@all_items.pluck(:name, :id))) %>
          <%#= f.submit "select" %>
        <% end %>
      </div>
      <div class="arrow-up">
        <%# Creates a CSS-based arrow %>
      </div>
      <div class="arrow-down">
        <%# Creates a CSS-based arrow %>
      </div>
      <div class="trade-middle-container">
        <div class="trade-middle-left">
          <div class= 'game-btn'>
            <%= link_to items_path do %>
              <span class="material-icons">home</span>
            <% end %>
          </div>
          <div id="list-items-button" class= 'game-btn'>
            <span class="material-icons">apps</span>
          </div>
        </div>
        <div id="drag-middle">
          <%= cl_image_tag @user_item.photos.first.key, class: "trade-picture-middle", alt: 'User Item'%>
        </div>
        <div class= 'game-btn' onclick="window.location.href = '/trades/new'">
          <span>SKIP</span>
        </div>
      </div>
    </div>
    <%= link_to item_path(@better_item.id) do %>
      <div id="drag-better" class="game-card">
        <% @item = @better_item %>
        <%= render "shared/carousel" %>
      </div>
    <% end %>
    <%= form_with(model: @better_trade, id: "formBetter") do |f| %>
      <%= f.hidden_field :item_1_id %>
      <%= f.hidden_field :item_2_id %>
    <% end %>
  </div>
  <div id="trade-items-list">
    <div id="trade-items-list-exit-btn" class= 'game-btn'>
      <span class="material-icons">close</span>
    </div>
    <% current_user.items.each do |item| %>
      <a href="#" data-item-id="<%= item.id %>" class="popup-menu-item">
        <%=cl_image_tag item.photos.last.key, class:"trade-item-selection" if item.photos.attached? %>
      </a>
    <% end %>
  </div>
</div>

app/views/trades/show.html.erb
<div class ="row justify-content-center d-flex chat-trades">
<%=image_tag(@trade.item_1.photos.first, :class => "trade-65")%>
<div><span class="material-icons" style="font-size: 50px;">
sync_alt
</span></div>
<%=image_tag(@trade.item_2.photos.first, :class => "trade-65")%>
</div>
<div class ="">
  <div class='row justify-content-center d-flex'>
    <div class="trade-complete">
      <%= link_to items_path do %>
          MARK TRADE COMPLETED
        <% end %>
      </div>
    </div>
    <div class='row justify-content-center d-flex'>
    <strong><P>TRADE PENDING</P></strong>
  </div>
  </div>
<div class="chat-container">
<div id="messages" data-trade-id="<%= @trade.id %>">
  <% @trade.messages.each do |message| %>
    <div class="message-container" id="message-<%= message.id %>">
      <i class="author">
        <div class="d-flex single-message">
        <%=image_tag(message.user.photo, :class => "avatar-55")%>
        <div class="flex-column">
        <div class="user-name">
        <span><%= message.user.name %></span>
        <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
      </i>
      <p><%= message.message %></p>
    </div>
  </div>
  </div>
  </div>
  <% end %>
</div>

<div d-flex>
<!-- <form action="/trades"></form> -->
<%= simple_form_for [@trade, @message], remote: true, class:"stick d-flex" do |f|%>
  <%= f.input :message, label: false, placeholder: "Message" %>
   <div class="input-group-append">
  <%= f.button :submit,'>', class:"outline-btn" %>
   </div>
<% end %>
</div>
</div>


send
</span>